<?php

/*
|--------------------------------------------------------------------------
| Phase 2 — Luxury Kenya safari itineraries
|--------------------------------------------------------------------------
| Merged into the main SEO page registry by App\Support\SeoPageRegistry.
| Each page uses the "itinerary" template and carries day-by-day content,
| facts, inclusions/exclusions and TouristTrip structured data.
*/

$inclusions = [
    'Private safari guide and 4x4 vehicle throughout',
    'Handpicked luxury camps and lodges',
    'Internal bush flights between regions',
    'Park, conservancy and concession fees',
    'Full-board meals as per itinerary',
    'All airport and airstrip transfers',
    'Drinking water in the safari vehicle',
    'Emergency evacuation cover',
];

$exclusions = [
    'International flights and visas',
    'Travel and medical insurance',
    'Premium wines, spirits and champagne',
    'Optional balloon safari and spa treatments',
    'Gratuities for guides and camp staff',
    'Items of a personal nature',
];

return [

    'safaris/7-day-luxury-kenya-safari' => [
        'locale' => 'en',
        'group' => 'safaris/7-day-luxury-kenya-safari',
        'template' => 'itinerary',
        'eyebrow' => 'Seven days, two regions',
        'h1' => '7-Day Luxury Kenya Safari',
        'title' => '7 Day Luxury Kenya Safari | Private Masai Mara & Laikipia',
        'description' => 'A private 7-day luxury Kenya safari combining the Masai Mara and Laikipia, with expert guides, handpicked camps and seamless bush flights.',
        'subtitle' => 'A concise, private introduction to Kenya — the wildlife drama of the Masai Mara balanced with the quiet exclusivity of Laikipia, all linked by bush flights.',
        'hero_image' => 'images/mara-sunset.jpg',
        'hero_alt' => 'Seven-day luxury Kenya safari in the Masai Mara',
        'facts' => [
            ['label' => 'Duration', 'value' => '7 days / 6 nights'],
            ['label' => 'Regions', 'value' => 'Masai Mara · Laikipia'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Balanced'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Met on arrival and transferred to a boutique Nairobi hotel or directly to Wilson Airport for your onward flight.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'A short bush flight to a Mara airstrip, then straight into camp for lunch and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Full day in the Mara', 'text' => 'Dawn and late-afternoon drives tracking lion, cheetah and leopard, with a private picnic in the bush.'],
            ['day' => 'Day 4', 'title' => 'Mara to Laikipia', 'text' => 'Morning game drive, then a scenic flight north to a private Laikipia conservancy.'],
            ['day' => 'Day 5', 'title' => 'Laikipia conservancy', 'text' => 'Off-road and night game drives, rhino and big-cat tracking, and time to slow down in camp.'],
            ['day' => 'Day 6', 'title' => 'Wildlife and walking', 'text' => 'A guided walk or camel ride, followed by an afternoon drive and a private sundowner on the plains.'],
            ['day' => 'Day 7', 'title' => 'Depart Kenya', 'text' => 'A final morning activity, then a bush flight to Nairobi for your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Two landscapes, one seamless week',
                'paragraphs' => [
                    'Seven days is enough for a genuinely memorable safari when the routing is tight. We pair the Mara\'s prolific predators with a private Laikipia conservancy, and use bush flights so travel time never eats into game viewing.',
                    'The result is a private, unhurried week suited to first-time visitors and seasoned safari-goers alike.',
                ],
                'bullets' => [
                    'Classic Mara wildlife with low-density conservancy privacy',
                    'Private guide and vehicle throughout',
                    'Bush flights instead of long road transfers',
                    'Ideal short-safari window for USA, UK and European travellers',
                ],
            ],
            [
                'kicker' => 'Best time',
                'title' => 'When to travel',
                'paragraphs' => [
                    'July to October is peak for the Great Migration and dry-season game viewing. January to March offers warm weather and excellent big-cat sightings with fewer visitors.',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'Is 7 days enough for a luxury Kenya safari?', 'a' => 'Yes. With bush flights, seven days allows two contrasting regions and four to five full game-viewing days without feeling rushed.'],
            ['q' => 'Can this itinerary be adjusted?', 'a' => 'Every element is flexible — regions, camps, pace and activities are tailored to you before confirmation.'],
            ['q' => 'What does the 7-day safari cost?', 'a' => 'Private luxury safaris of this length typically start around USD 8,000 per person, depending on season, camp tier and group size.'],
            ['q' => 'Is it suitable for families?', 'a' => 'Yes, and the shorter duration often suits younger travellers. We choose family-friendly camps and flexible pacing.'],
        ],
        'related' => ['kenya-luxury-safari-packages', 'luxury-kenya-safaris', 'safaris/masai-mara-laikipia', 'fly-in-safaris-kenya'],
    ],

    'safaris/8-day-luxury-kenya-safari' => [
        'locale' => 'en',
        'group' => 'safaris/8-day-luxury-kenya-safari',
        'template' => 'itinerary',
        'eyebrow' => 'Eight unhurried days',
        'h1' => '8-Day Luxury Kenya Safari',
        'title' => '8 Day Luxury Kenya Safari | Private Tailor-Made Itinerary',
        'description' => 'An eight-day private luxury Kenya safari linking the Masai Mara with Laikipia, guided throughout and arranged end to end by Kenya-based specialists.',
        'subtitle' => 'A little more room to breathe — eight private days across the Masai Mara and Laikipia, with time for deeper game viewing and quiet conservancy experiences.',
        'hero_image' => 'images/safari-air.jpg',
        'hero_alt' => 'Eight-day private luxury Kenya safari by bush flight',
        'facts' => [
            ['label' => 'Duration', 'value' => '8 days / 7 nights'],
            ['label' => 'Regions', 'value' => 'Masai Mara · Laikipia'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Relaxed'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer to a boutique hotel for a comfortable first night in Kenya.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon game drive as the light softens over the plains.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Extended morning and evening drives with your private guide, following the best wildlife of the day.'],
            ['day' => 'Day 4', 'title' => 'Mara at leisure', 'text' => 'A relaxed day with a bush breakfast, optional balloon safari and a private river-side sundowner.'],
            ['day' => 'Day 5', 'title' => 'Mara to Laikipia', 'text' => 'Fly north to a private conservancy, arriving in time for lunch and an afternoon drive.'],
            ['day' => 'Day 6', 'title' => 'Laikipia wildlife', 'text' => 'Off-road and night drives, rhino tracking and the chance to see species rare elsewhere.'],
            ['day' => 'Day 7', 'title' => 'Conservation in action', 'text' => 'Guided walk, camel ride or conservation experience, followed by a final sundowner.'],
            ['day' => 'Day 8', 'title' => 'Depart Kenya', 'text' => 'Morning at leisure, then a flight to Nairobi for your onward journey.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'The ideal first luxury safari',
                'paragraphs' => [
                    'Eight days is the sweet spot for many travellers — long enough for two regions and genuine downtime, short enough to fit neatly into a holiday calendar.',
                    'We use the extra day for slower, richer experiences: a balloon flight over the Mara, a guided walk in Laikipia, or simply more time at a sighting.',
                ],
                'bullets' => [
                    'Two contrasting regions with built-in rest time',
                    'Private guiding and flexible daily plans',
                    'Optional balloon safari and conservation experiences',
                    'Smooth bush-flight connections throughout',
                ],
            ],
            [
                'kicker' => 'Accommodation',
                'title' => 'Where you stay',
                'paragraphs' => [
                    'We handpick intimate tented camps and boutique lodges chosen for location, guiding and service, matching style to your preferences.',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'How does 8 days compare with 7?', 'a' => 'The extra night usually adds a full day in one region, giving more relaxed pacing and a better chance of key sightings.'],
            ['q' => 'Can we add the coast?', 'a' => 'Yes, though for a beach extension we normally recommend 10 days or more so both halves feel unhurried.'],
            ['q' => 'When is the best time for this trip?', 'a' => 'July to October for the Migration; January to March for warm weather and superb big-cat viewing.'],
            ['q' => 'Do we get the same guide throughout?', 'a' => 'Where logistics allow, yes. Regional specialists may join for particular conservancy experiences.'],
        ],
        'related' => ['kenya-luxury-safari-packages', 'safaris/7-day-luxury-kenya-safari', 'safaris/masai-mara-laikipia', 'luxury-kenya-safaris'],
    ],

    'safaris/10-day-luxury-kenya-safari' => [
        'locale' => 'en',
        'group' => 'safaris/10-day-luxury-kenya-safari',
        'template' => 'itinerary',
        'eyebrow' => 'Ten days, three regions',
        'h1' => '10-Day Luxury Kenya Safari',
        'title' => '10 Day Luxury Kenya Safari | Private Multi-Region Itinerary',
        'description' => 'A ten-day private luxury Kenya safari across the Masai Mara, Laikipia and Amboseli, with expert guides, bush flights and handpicked luxury camps.',
        'subtitle' => 'Ten private days across three of Kenya\'s finest regions — the Masai Mara, Laikipia and Amboseli — with time to travel slowly and see it properly.',
        'hero_image' => 'images/safari-elephant.jpg',
        'hero_alt' => 'Ten-day luxury Kenya safari with elephants in Amboseli',
        'facts' => [
            ['label' => 'Duration', 'value' => '10 days / 9 nights'],
            ['label' => 'Regions', 'value' => 'Mara · Laikipia · Amboseli'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Relaxed'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer to a boutique hotel and time to rest before the safari begins.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'A bush flight to the Mara, lunch in camp and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Track big cats across the plains with your private guide and a bush picnic lunch.'],
            ['day' => 'Day 4', 'title' => 'Mara to Laikipia', 'text' => 'Morning drive, then a scenic flight north to a private Laikipia conservancy.'],
            ['day' => 'Day 5', 'title' => 'Laikipia conservancy', 'text' => 'Off-road and night drives, rhino and predator tracking, and quiet time in camp.'],
            ['day' => 'Day 6', 'title' => 'Laikipia experiences', 'text' => 'A guided walk or camel ride and a private sundowner overlooking the plains.'],
            ['day' => 'Day 7', 'title' => 'Fly to Amboseli', 'text' => 'Fly south to Amboseli for big skies, elephant herds and Mount Kilimanjaro views.'],
            ['day' => 'Day 8', 'title' => 'Amboseli full day', 'text' => 'Dawn and afternoon drives among elephants, with photography-focused positioning.'],
            ['day' => 'Day 9', 'title' => 'Amboseli at leisure', 'text' => 'A gentle morning drive, a visit to a Maasai community, and a final sundowner.'],
            ['day' => 'Day 10', 'title' => 'Depart Kenya', 'text' => 'A last morning in the bush, then a flight to Nairobi for your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Three regions, one elegant arc',
                'paragraphs' => [
                    'Ten days lets you experience the contrast that makes Kenya so rewarding: the predator-rich Mara, the private wilderness of Laikipia and the elephant country of Amboseli.',
                    'Bush flights keep the transitions short, so the extra days go into wildlife and rest rather than roads.',
                ],
                'bullets' => [
                    'The three defining regions of a Kenya safari',
                    'Private guiding and 4x4 throughout',
                    'Photography-friendly Amboseli light and Kilimanjaro',
                    'Comfortable pacing with genuine downtime',
                ],
            ],
            [
                'kicker' => 'Best time',
                'title' => 'When to travel',
                'paragraphs' => [
                    'The dry seasons (July–October and January–February) give the most reliable game viewing and the clearest mountain views in Amboseli.',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'Is 10 days too long?', 'a' => 'Rarely. With bush flights and relaxed pacing, ten days feels spacious rather than long, and most travellers are reluctant to leave.'],
            ['q' => 'Which regions do you recommend first?', 'a' => 'The Mara, Laikipia and Amboseli form the classic first-timer arc; Samburu and the coast suit repeat visitors.'],
            ['q' => 'What is the cost of a 10-day safari?', 'a' => 'Private luxury 10-day safaris typically range from around USD 10,000 to USD 18,000 per person, depending on season, camps and group size.'],
            ['q' => 'Can we include the coast?', 'a' => 'Yes, and at ten days a short beach finish is possible. We will advise on the best split for your flights.'],
        ],
        'related' => ['kenya-luxury-safari-packages', 'safaris/12-day-luxury-kenya-safari', 'safaris/masai-mara-amboseli', 'luxury-kenya-safaris'],
    ],

    'safaris/12-day-luxury-kenya-safari' => [
        'locale' => 'en',
        'group' => 'safaris/12-day-luxury-kenya-safari',
        'template' => 'itinerary',
        'eyebrow' => 'Twelve days of depth',
        'h1' => '12-Day Luxury Kenya Safari',
        'title' => '12 Day Luxury Kenya Safari | Private Kenya Safari Circuit',
        'description' => 'A twelve-day private luxury Kenya safari through the Mara, Laikipia and Samburu, designed for travellers who want depth, privacy and unhurried pacing.',
        'subtitle' => 'For travellers who want to go deeper — twelve private days across the Masai Mara, Laikipia and the wild north of Samburu, at a genuinely unhurried pace.',
        'hero_image' => 'images/giraffe-herd.jpg',
        'hero_alt' => 'Twelve-day luxury Kenya safari with giraffes',
        'facts' => [
            ['label' => 'Duration', 'value' => '12 days / 11 nights'],
            ['label' => 'Regions', 'value' => 'Mara · Laikipia · Samburu'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Unhurried'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night before the safari begins.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara, lunch in camp and an afternoon drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Dawn and golden-hour drives tracking lion, cheetah and leopard.'],
            ['day' => 'Day 4', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and time to enjoy camp.'],
            ['day' => 'Day 5', 'title' => 'Mara to Laikipia', 'text' => 'Fly north to a private conservancy for off-road and night drives.'],
            ['day' => 'Day 6', 'title' => 'Laikipia wildlife', 'text' => 'Rhino, big cats and specialised northern species on a private conservancy.'],
            ['day' => 'Day 7', 'title' => 'Laikipia experiences', 'text' => 'Guided walk, camel ride or lion-tracking with researchers.'],
            ['day' => 'Day 8', 'title' => 'Fly to Samburu', 'text' => 'Fly further north to Samburu for arid, photogenic wilderness and the Special Five.'],
            ['day' => 'Day 9', 'title' => 'Samburu full day', 'text' => 'Game drives along the Ewaso Ng\'iro river and a cultural visit if you wish.'],
            ['day' => 'Day 10', 'title' => 'Samburu at leisure', 'text' => 'A slower day of drives, river wildlife and private sundowners.'],
            ['day' => 'Day 11', 'title' => 'Samburu to Nairobi', 'text' => 'Morning drive, then fly to Nairobi for a final night.'],
            ['day' => 'Day 12', 'title' => 'Depart Kenya', 'text' => 'Transfer to the airport for your international flight home.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'The connoisseur\'s Kenya circuit',
                'paragraphs' => [
                    'Twelve days allows a truly varied journey: the Mara\'s predators, Laikipia\'s private conservancies and Samburu\'s remote, otherworldly north.',
                    'The extra time is spent at a slower pace — longer sightings, more walks and genuine rest between regions.',
                ],
                'bullets' => [
                    'Three contrasting ecosystems in one journey',
                    'Time for walking, conservation and photography',
                    'Private guiding and flexible daily plans',
                    'Samburu\'s Special Five and rich culture',
                ],
            ],
            [
                'kicker' => 'Traveller types',
                'title' => 'Who this suits',
                'paragraphs' => [
                    'This itinerary suits repeat safari-goers, photographers and travellers celebrating a special occasion who value depth over distance covered.',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'Why include Samburu?', 'a' => 'Samburu adds a different landscape, the Special Five species and a quieter, more exclusive atmosphere than the southern parks.'],
            ['q' => 'Is 12 days good for photographers?', 'a' => 'Excellent. The length allows early starts, extended golden-hour drives and time in reserves with fewer vehicles.'],
            ['q' => 'Can we swap Samburu for the coast?', 'a' => 'Yes. We can redesign the second half as a beach extension if you prefer an ocean finish.'],
            ['q' => 'How much does a 12-day safari cost?', 'a' => 'Private luxury 12-day safaris typically range from around USD 12,000 to USD 22,000 per person, depending on season, camp tier and group size.'],
        ],
        'related' => ['kenya-luxury-safari-packages', 'safaris/samburu-laikipia-masai-mara', 'safaris/14-day-luxury-kenya-safari', 'destinations/samburu'],
    ],

    'safaris/14-day-luxury-kenya-safari' => [
        'locale' => 'en',
        'group' => 'safaris/14-day-luxury-kenya-safari',
        'template' => 'itinerary',
        'eyebrow' => 'The complete Kenya journey',
        'h1' => '14-Day Luxury Kenya Safari',
        'title' => '14 Day Luxury Kenya Safari | The Complete Kenya Journey',
        'description' => 'A fourteen-day private luxury Kenya safari combining the Masai Mara, Laikipia, Samburu, Amboseli and the Indian Ocean coast in one seamless journey.',
        'subtitle' => 'The complete Kenya journey — fourteen private days linking the Masai Mara, Laikipia, Samburu and Amboseli, with a barefoot finish on the Indian Ocean.',
        'hero_image' => 'images/hero-samburu.jpg',
        'hero_alt' => 'Fourteen-day luxury Kenya safari and beach journey',
        'facts' => [
            ['label' => 'Duration', 'value' => '14 days / 13 nights'],
            ['label' => 'Regions', 'value' => 'Mara · Laikipia · Samburu · Amboseli · Coast'],
            ['label' => 'Style', 'value' => 'Private fly-in safari & beach'],
            ['label' => 'Pace', 'value' => 'Unhurried'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night in Kenya.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Extended drives tracking the Mara\'s big cats and plains game.'],
            ['day' => 'Day 4', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and quiet time in camp.'],
            ['day' => 'Day 5', 'title' => 'Mara to Laikipia', 'text' => 'Fly north to a private conservancy for off-road game viewing.'],
            ['day' => 'Day 6', 'title' => 'Laikipia wildlife', 'text' => 'Rhino and predator tracking in a low-density conservancy.'],
            ['day' => 'Day 7', 'title' => 'Laikipia experiences', 'text' => 'Guided walk, camel ride or conservation encounter.'],
            ['day' => 'Day 8', 'title' => 'Fly to Samburu', 'text' => 'Head north for arid wilderness and the Special Five species.'],
            ['day' => 'Day 9', 'title' => 'Samburu full day', 'text' => 'River-front game drives and an optional community visit.'],
            ['day' => 'Day 10', 'title' => 'Samburu to Amboseli', 'text' => 'A scenic flight south to Amboseli for elephants and Kilimanjaro views.'],
            ['day' => 'Day 11', 'title' => 'Amboseli full day', 'text' => 'Dawn and afternoon drives among elephant herds and big skies.'],
            ['day' => 'Day 12', 'title' => 'Fly to the coast', 'text' => 'Fly to Diani or Watamu and transfer to your beach retreat.'],
            ['day' => 'Day 13', 'title' => 'Indian Ocean', 'text' => 'A full day to relax, swim, dive or sail on the Kenyan coast.'],
            ['day' => 'Day 14', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi and connect with your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Kenya in full, from bush to beach',
                'paragraphs' => [
                    'Fourteen days is the definitive Kenya safari. You experience four great wildlife regions and then decompress on the Indian Ocean, flying between every stage.',
                    'It is an ideal choice for a milestone trip, a long-awaited first safari, or travellers who may not return soon and want to see Kenya properly.',
                ],
                'bullets' => [
                    'Four iconic safari regions plus the coast',
                    'Private guiding and bush flights throughout',
                    'Time for photography, walking and conservation',
                    'A restorative Indian Ocean finale',
                ],
            ],
            [
                'kicker' => 'Best time',
                'title' => 'When to travel',
                'paragraphs' => [
                    'July to October delivers the Migration and excellent coast conditions. January to March offers warm, dry weather across both safari and beach.',
                ],
            ],
        ],
        'inclusions' => array_merge($inclusions, ['Beach accommodation on a half-board basis']),
        'exclusions' => array_merge($exclusions, ['Beach activities and watersports']),
        'faqs' => [
            ['q' => 'Is 14 days too long for a safari?', 'a' => 'Not when it includes the coast. The beach finale gives the trip a natural rest, so the safari days stay fresh and exciting.'],
            ['q' => 'Where on the coast do you recommend?', 'a' => 'Diani offers white sand and easy access; Watamu brings reefs and marine life; Zanzibar suits a different cultural flavour.'],
            ['q' => 'Can we reduce the safari to add more beach?', 'a' => 'Yes, we balance safari and beach nights to suit your flights and how much relaxation you want.'],
            ['q' => 'What does a 14-day journey cost?', 'a' => 'Private luxury 14-day safaris with a beach finish typically range from around USD 15,000 to USD 28,000 per person, depending on season, camps and group size.'],
        ],
        'related' => ['luxury-safari-and-beach-kenya', 'safaris/masai-mara-amboseli-diani', 'kenya-luxury-safari-packages', 'luxury-honeymoon-safaris-kenya'],
    ],

    'safaris/masai-mara-laikipia' => [
        'locale' => 'en',
        'group' => 'safaris/masai-mara-laikipia',
        'template' => 'itinerary',
        'eyebrow' => 'Predators and privacy',
        'h1' => 'Masai Mara & Laikipia Safari',
        'title' => 'Masai Mara & Laikipia Safari | Private Luxury Kenya Circuit',
        'description' => 'A private Masai Mara and Laikipia safari pairing legendary wildlife with secluded conservancies. Expert guiding, luxury camps and bush flights.',
        'subtitle' => 'Pair the celebrated wildlife of the Masai Mara with the private, conservation-led wilderness of Laikipia — the perfect contrast of drama and exclusivity.',
        'hero_image' => 'images/safari-lion-drive.jpg',
        'hero_alt' => 'Private Masai Mara and Laikipia safari in Kenya',
        'facts' => [
            ['label' => 'Duration', 'value' => '7 days / 6 nights'],
            ['label' => 'Regions', 'value' => 'Masai Mara · Laikipia'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Balanced'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer to a boutique hotel ahead of the safari.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Private game drives tracking lion, cheetah and leopard.'],
            ['day' => 'Day 4', 'title' => 'Mara to Laikipia', 'text' => 'Fly to a private conservancy for off-road and night drives.'],
            ['day' => 'Day 5', 'title' => 'Laikipia wildlife', 'text' => 'Rhino and predator tracking across a vast private landscape.'],
            ['day' => 'Day 6', 'title' => 'Laikipia experiences', 'text' => 'A guided walk or camel ride, then a private sundowner.'],
            ['day' => 'Day 7', 'title' => 'Depart Kenya', 'text' => 'Morning activity, then fly to Nairobi for your departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'The perfect pairing',
                'paragraphs' => [
                    'The Mara delivers the iconic wildlife and, in season, the Great Migration. Laikipia adds privacy, low vehicle density and conservation-led experiences that the busier parks cannot match.',
                    'Together they offer the best of both — famous wildlife and genuine exclusivity — in a compact, fly-in week.',
                ],
                'bullets' => [
                    'World-class predator viewing in the Mara',
                    'Exclusive conservancies with off-road and night drives',
                    'Conservation-led experiences and walking',
                    'Short bush flights between regions',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'Which comes first, the Mara or Laikipia?', 'a' => 'We usually start in the Mara for the iconic wildlife, then unwind in Laikipia, though the order can be reversed to suit flights.'],
            ['q' => 'Can we see rhino in Laikipia?', 'a' => 'Yes, Laikipia\'s conservancies are among Kenya\'s best places to see both black and white rhino.'],
            ['q' => 'Is this a good honeymoon itinerary?', 'a' => 'Very much so — the mix of wildlife and privacy works beautifully for couples.'],
            ['q' => 'Can the trip be lengthened?', 'a' => 'Yes, we can add a third region, extra nights, or a coast extension.'],
        ],
        'related' => ['destinations/laikipia', 'destinations/masai-mara', 'safaris/lewa-masai-mara', 'luxury-kenya-safaris'],
    ],

    'safaris/masai-mara-amboseli' => [
        'locale' => 'en',
        'group' => 'safaris/masai-mara-amboseli',
        'template' => 'itinerary',
        'eyebrow' => 'Big cats and elephants',
        'h1' => 'Masai Mara & Amboseli Safari',
        'title' => 'Masai Mara & Amboseli Safari | Private Luxury Kenya Itinerary',
        'description' => 'A private Masai Mara and Amboseli safari combining big-cat country with iconic elephants beneath Kilimanjaro. Luxury camps and expert guides.',
        'subtitle' => 'Two of Kenya\'s most photogenic wildernesses in one private journey — the predator-rich Masai Mara and the elephant country of Amboseli.',
        'hero_image' => 'images/safari-elephant.jpg',
        'hero_alt' => 'Private Masai Mara and Amboseli safari with elephants',
        'facts' => [
            ['label' => 'Duration', 'value' => '7 days / 6 nights'],
            ['label' => 'Regions', 'value' => 'Masai Mara · Amboseli'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Balanced'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Dawn and golden-hour drives in search of big cats.'],
            ['day' => 'Day 4', 'title' => 'Mara to Amboseli', 'text' => 'Fly south to Amboseli for elephants and Kilimanjaro views.'],
            ['day' => 'Day 5', 'title' => 'Amboseli full day', 'text' => 'Dawn and afternoon drives among elephant herds and big skies.'],
            ['day' => 'Day 6', 'title' => 'Amboseli at leisure', 'text' => 'A relaxed morning drive, a Maasai community visit and a final sundowner.'],
            ['day' => 'Day 7', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi for your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'The classic photographer\'s pairing',
                'paragraphs' => [
                    'The Mara offers the highest densities of big cats in Africa; Amboseli offers the continent\'s most photogenic elephants set against Kilimanjaro.',
                    'Together they make a superb short safari for travellers who care about wildlife imagery and dramatic landscapes.',
                ],
                'bullets' => [
                    'Big-cat drama in the Masai Mara',
                    'Iconic elephant herds with Kilimanjaro backdrops',
                    'Photography-friendly light in both regions',
                    'Private guide and 4x4 throughout',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'Will we see Kilimanjaro?', 'a' => 'On clear mornings, yes. Cloud can obscure the summit, so we allow multiple viewing opportunities.'],
            ['q' => 'How do we travel between the two?', 'a' => 'A short bush flight connects the Mara and Amboseli, avoiding a long road transfer.'],
            ['q' => 'Is this suitable for first-time visitors?', 'a' => 'Absolutely — it is one of the strongest introductions to Kenya.'],
            ['q' => 'Can we add the coast?', 'a' => 'Yes, a Diani or Watamu extension works well and we can extend the itinerary accordingly.'],
        ],
        'related' => ['destinations/amboseli', 'destinations/masai-mara', 'safaris/masai-mara-amboseli-diani', 'luxury-kenya-safaris'],
    ],

    'safaris/samburu-laikipia-masai-mara' => [
        'locale' => 'en',
        'group' => 'safaris/samburu-laikipia-masai-mara',
        'template' => 'itinerary',
        'eyebrow' => 'North to south',
        'h1' => 'Samburu, Laikipia & Masai Mara Safari',
        'title' => 'Samburu Laikipia Masai Mara Safari | Luxury Northern Kenya',
        'description' => 'A private Samburu, Laikipia and Masai Mara safari through Kenya\'s most varied regions, with exclusive conservancies and expert guiding.',
        'subtitle' => 'Three extraordinary regions in one private journey — the arid north of Samburu, the private wilderness of Laikipia and the legendary wildlife of the Masai Mara.',
        'hero_image' => 'images/samburu-elephant.jpg',
        'hero_alt' => 'Samburu Laikipia and Masai Mara private safari',
        'facts' => [
            ['label' => 'Duration', 'value' => '10 days / 9 nights'],
            ['label' => 'Regions', 'value' => 'Samburu · Laikipia · Masai Mara'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Relaxed'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a comfortable first night.'],
            ['day' => 'Day 2', 'title' => 'Fly to Samburu', 'text' => 'Head north to arid wilderness and the Special Five species.'],
            ['day' => 'Day 3', 'title' => 'Samburu full day', 'text' => 'River-front game drives and an optional cultural visit.'],
            ['day' => 'Day 4', 'title' => 'Samburu to Laikipia', 'text' => 'Fly south to a private Laikipia conservancy.'],
            ['day' => 'Day 5', 'title' => 'Laikipia wildlife', 'text' => 'Rhino and predator tracking in a low-density landscape.'],
            ['day' => 'Day 6', 'title' => 'Laikipia experiences', 'text' => 'Guided walk, camel ride or conservation encounter.'],
            ['day' => 'Day 7', 'title' => 'Fly to the Masai Mara', 'text' => 'Fly to the Mara for its celebrated big-cat viewing.'],
            ['day' => 'Day 8', 'title' => 'Mara full day', 'text' => 'Extended drives tracking lion, cheetah and leopard.'],
            ['day' => 'Day 9', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and a final sundowner.'],
            ['day' => 'Day 10', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi for your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Kenya\'s greatest contrasts',
                'paragraphs' => [
                    'This route sweeps from the red-earth north to the golden plains of the Mara, taking in private conservancies and remote reserves along the way.',
                    'It is an itinerary for travellers who want variety, exclusivity and the sense of a true expedition without ever compromising comfort.',
                ],
                'bullets' => [
                    'Three contrasting ecosystems',
                    'Samburu\'s Special Five and rich culture',
                    'Private conservancy exclusivity in Laikipia',
                    'The Mara\'s world-class predators',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'What order is best?', 'a' => 'Many travellers prefer north to south, ending with the Mara, but we can sequence it to suit your flights.'],
            ['q' => 'Is Samburu very remote?', 'a' => 'It feels wonderfully remote, yet is an easy bush flight from Nairobi and Laikipia.'],
            ['q' => 'How does this compare to a 12-day trip?', 'a' => 'This ten-day version covers the same regions with slightly tighter pacing; the twelve-day adds rest and depth.'],
            ['q' => 'Can children join?', 'a' => 'Yes, we match camps and pacing to your family, and the variety keeps younger travellers engaged.'],
        ],
        'related' => ['destinations/samburu', 'destinations/laikipia', 'safaris/12-day-luxury-kenya-safari', 'luxury-kenya-safaris'],
    ],

    'safaris/masai-mara-amboseli-diani' => [
        'locale' => 'en',
        'group' => 'safaris/masai-mara-amboseli-diani',
        'template' => 'itinerary',
        'eyebrow' => 'Wildlife then ocean',
        'h1' => 'Masai Mara, Amboseli & Diani Safari',
        'title' => 'Masai Mara Amboseli Diani Safari | Kenya Safari & Beach',
        'description' => 'A private Masai Mara, Amboseli and Diani Beach safari combining world-class wildlife with barefoot Indian Ocean relaxation.',
        'subtitle' => 'The safari-and-beach classic — big cats and elephants in the Mara and Amboseli, then the white sands of Diani Beach to finish.',
        'hero_image' => 'images/tsavo-giraffes.jpg',
        'hero_alt' => 'Masai Mara Amboseli and Diani beach safari',
        'facts' => [
            ['label' => 'Duration', 'value' => '11 days / 10 nights'],
            ['label' => 'Regions', 'value' => 'Mara · Amboseli · Diani Beach'],
            ['label' => 'Style', 'value' => 'Private safari & beach'],
            ['label' => 'Pace', 'value' => 'Relaxed'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Private drives tracking the Mara\'s big cats.'],
            ['day' => 'Day 4', 'title' => 'Mara to Amboseli', 'text' => 'Fly south to Amboseli for elephants and Kilimanjaro views.'],
            ['day' => 'Day 5', 'title' => 'Amboseli full day', 'text' => 'Dawn and afternoon drives among elephant herds.'],
            ['day' => 'Day 6', 'title' => 'Amboseli at leisure', 'text' => 'A gentle morning drive and a final bush sundowner.'],
            ['day' => 'Day 7', 'title' => 'Fly to Diani Beach', 'text' => 'Transfer to the coast and your beach retreat on the Indian Ocean.'],
            ['day' => 'Day 8', 'title' => 'Diani Beach', 'text' => 'A full day to relax, swim, dive or sail.'],
            ['day' => 'Day 9', 'title' => 'Diani Beach', 'text' => 'Time for a dhow cruise, snorkelling or a spa afternoon.'],
            ['day' => 'Day 10', 'title' => 'Diani at leisure', 'text' => 'A final unhurried day by the ocean.'],
            ['day' => 'Day 11', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi and connect with your international flight.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'The perfect safari-and-beach balance',
                'paragraphs' => [
                    'This itinerary gives equal weight to wildlife and rest. Two great safari regions deliver the big game, then Diani Beach offers warm water, white sand and unhurried days.',
                    'All connections are by air, so the transition from bush to beach is seamless.',
                ],
                'bullets' => [
                    'Two premier safari regions plus the coast',
                    'Seamless bush-to-beach flights',
                    'Calm, reef-protected Diani waters',
                    'Ideal for couples and families',
                ],
            ],
        ],
        'inclusions' => array_merge($inclusions, ['Beach accommodation on a half-board basis']),
        'exclusions' => array_merge($exclusions, ['Beach activities and watersports']),
        'faqs' => [
            ['q' => 'How many beach nights should we have?', 'a' => 'Four nights on the coast is a comfortable minimum; five or more if you really want to unwind.'],
            ['q' => 'Is Diani good for families?', 'a' => 'Yes — the reef-protected water is calm and shallow, ideal for children.'],
            ['q' => 'Can we choose a different beach?', 'a' => 'Certainly. Watamu and the Zanzibar archipelago are excellent alternatives.'],
            ['q' => 'When is the best time?', 'a' => 'January to March and July to October combine dry-season safari with lovely coast conditions.'],
        ],
        'related' => ['luxury-safari-and-beach-kenya', 'safaris/masai-mara-diani', 'safaris/14-day-luxury-kenya-safari', 'destinations/masai-mara'],
    ],

    'safaris/lewa-masai-mara' => [
        'locale' => 'en',
        'group' => 'safaris/lewa-masai-mara',
        'template' => 'itinerary',
        'eyebrow' => 'Conservation and drama',
        'h1' => 'Lewa & Masai Mara Safari',
        'title' => 'Lewa & Masai Mara Safari | Luxury Conservation & Wildlife',
        'description' => 'A private Lewa and Masai Mara safari pairing a UNESCO-listed rhino conservancy with the legendary wildlife of the Mara.',
        'subtitle' => 'Combine the conservation triumph of Lewa with the wildlife spectacle of the Masai Mara — rhino and private conservancy calm, then big-cat drama.',
        'hero_image' => 'images/safari-air.jpg',
        'hero_alt' => 'Lewa Conservancy and Masai Mara private safari',
        'facts' => [
            ['label' => 'Duration', 'value' => '7 days / 6 nights'],
            ['label' => 'Regions', 'value' => 'Lewa · Masai Mara'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Balanced'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night.'],
            ['day' => 'Day 2', 'title' => 'Fly to Lewa', 'text' => 'Fly north to the conservancy and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Lewa full day', 'text' => 'Rhino tracking with rangers and big-cat viewing on the conservancy.'],
            ['day' => 'Day 4', 'title' => 'Lewa to the Masai Mara', 'text' => 'Fly to the Mara and settle into camp for an evening drive.'],
            ['day' => 'Day 5', 'title' => 'Mara full day', 'text' => 'Extended private drives tracking lion, cheetah and leopard.'],
            ['day' => 'Day 6', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and a final sundowner.'],
            ['day' => 'Day 7', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi for your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Conservation with a front-row seat',
                'paragraphs' => [
                    'Lewa is one of Africa\'s great conservation success stories, inscribed as a UNESCO World Heritage site. Its rhino populations and private guiding make for a deeply rewarding stay.',
                    'The Masai Mara then delivers the iconic wildlife and, in season, the Great Migration.',
                ],
                'bullets' => [
                    'World-class rhino viewing at Lewa',
                    'Big-cat drama in the Masai Mara',
                    'Conservation-led guiding and experiences',
                    'Short bush flights between regions',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'What makes Lewa special?', 'a' => 'Its UNESCO-listed conservation model, exceptional rhino viewing and deliberately limited visitor numbers.'],
            ['q' => 'Can we track rhino on foot?', 'a' => 'Guided rhino tracking with rangers is available and is a highlight for many travellers.'],
            ['q' => 'Is this trip good for photographers?', 'a' => 'Yes — Lewa\'s clean landscapes and the Mara\'s predator action are superb for photography.'],
            ['q' => 'Can the itinerary be extended?', 'a' => 'Yes, we can add Amboseli, Samburu or a coast extension.'],
        ],
        'related' => ['destinations/lewa', 'destinations/laikipia', 'safaris/masai-mara-laikipia', 'luxury-kenya-safaris'],
    ],

    'safaris/ol-pejeta-masai-mara' => [
        'locale' => 'en',
        'group' => 'safaris/ol-pejeta-masai-mara',
        'template' => 'itinerary',
        'eyebrow' => 'Rhino country to big cats',
        'h1' => 'Ol Pejeta & Masai Mara Safari',
        'title' => 'Ol Pejeta & Masai Mara Safari | Luxury Kenya Rhino Safari',
        'description' => 'A private Ol Pejeta and Masai Mara safari combining rhino conservation with Kenya\'s most famous big-cat wilderness.',
        'subtitle' => 'See conservation up close at Ol Pejeta — home to the world\'s last northern white rhinos — then experience the legendary wildlife of the Masai Mara.',
        'hero_image' => 'images/safari-giraffe.jpg',
        'hero_alt' => 'Ol Pejeta and Masai Mara private luxury safari',
        'facts' => [
            ['label' => 'Duration', 'value' => '7 days / 6 nights'],
            ['label' => 'Regions', 'value' => 'Ol Pejeta · Masai Mara'],
            ['label' => 'Style', 'value' => 'Private fly-in safari'],
            ['label' => 'Pace', 'value' => 'Balanced'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a comfortable first night.'],
            ['day' => 'Day 2', 'title' => 'Ol Pejeta', 'text' => 'Transfer or fly to Ol Pejeta and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Ol Pejeta full day', 'text' => 'Rhino sanctuary visit, chimpanzee sanctuary and big-cat viewing.'],
            ['day' => 'Day 4', 'title' => 'Ol Pejeta to the Masai Mara', 'text' => 'Fly to the Mara and settle into camp for an evening drive.'],
            ['day' => 'Day 5', 'title' => 'Mara full day', 'text' => 'Extended private drives tracking the Mara\'s predators.'],
            ['day' => 'Day 6', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and a final sundowner.'],
            ['day' => 'Day 7', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi for your international departure.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Conservation and classic safari',
                'paragraphs' => [
                    'Ol Pejeta is a leading private conservancy and the last refuge of the northern white rhino. Its sanctuaries give travellers a rare insight into frontline conservation.',
                    'The Masai Mara then supplies the quintessential safari drama, making this a journey with both meaning and spectacle.',
                ],
                'bullets' => [
                    'Rhino and chimpanzee sanctuaries at Ol Pejeta',
                    'World-class predator viewing in the Mara',
                    'Private guiding throughout',
                    'A safari with a genuine conservation focus',
                ],
            ],
        ],
        'inclusions' => $inclusions,
        'exclusions' => $exclusions,
        'faqs' => [
            ['q' => 'What is Ol Pejeta known for?', 'a' => 'It is East Africa\'s largest black-rhino sanctuary and home to the last two northern white rhinos, alongside a chimpanzee sanctuary.'],
            ['q' => 'Is Ol Pejeta suitable for children?', 'a' => 'Very — the sanctuaries and conservation activities are engaging and educational for families.'],
            ['q' => 'How do we get to Ol Pejeta?', 'a' => 'By road from Nairobi or by light aircraft; we arrange whichever suits your itinerary.'],
            ['q' => 'Can we combine this with the coast?', 'a' => 'Yes, we can add Diani or Watamu for a beach finale.'],
        ],
        'related' => ['destinations/laikipia', 'destinations/masai-mara', 'safaris/masai-mara-laikipia', 'luxury-kenya-safaris'],
    ],

    'safaris/masai-mara-diani' => [
        'locale' => 'en',
        'group' => 'safaris/masai-mara-diani',
        'template' => 'itinerary',
        'eyebrow' => 'Bush and beach',
        'h1' => 'Masai Mara & Diani Beach Safari',
        'title' => 'Masai Mara & Diani Beach Safari | Kenya Bush & Beach',
        'description' => 'A private Masai Mara and Diani Beach safari pairing big-cat game drives with the white sands of Kenya\'s south coast.',
        'subtitle' => 'The purest bush-and-beach escape — the wildlife of the Masai Mara followed by the white sands and warm waters of Diani Beach.',
        'hero_image' => 'images/mara-jeep.jpg',
        'hero_alt' => 'Masai Mara and Diani Beach safari holiday',
        'facts' => [
            ['label' => 'Duration', 'value' => '9 days / 8 nights'],
            ['label' => 'Regions', 'value' => 'Masai Mara · Diani Beach'],
            ['label' => 'Style', 'value' => 'Private safari & beach'],
            ['label' => 'Pace', 'value' => 'Relaxed'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Private drives tracking lion, cheetah and leopard.'],
            ['day' => 'Day 4', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and quiet time in camp.'],
            ['day' => 'Day 5', 'title' => 'Fly to Diani Beach', 'text' => 'Fly to the coast and transfer to your beach retreat.'],
            ['day' => 'Day 6', 'title' => 'Diani Beach', 'text' => 'A full day to relax, swim, dive or sail.'],
            ['day' => 'Day 7', 'title' => 'Diani Beach', 'text' => 'Dhow cruise, snorkelling or a spa afternoon.'],
            ['day' => 'Day 8', 'title' => 'Diani at leisure', 'text' => 'A final unhurried day by the ocean.'],
            ['day' => 'Day 9', 'title' => 'Depart Kenya', 'text' => 'Fly to Nairobi and connect with your international flight.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Two icons, one seamless trip',
                'paragraphs' => [
                    'The Masai Mara gives you the safari most people dream of; Diani Beach gives you the rest that makes it worthwhile.',
                    'A single bush flight connects the two, so the journey from game drive to sun lounger is effortless.',
                ],
                'bullets' => [
                    'Big-cat wildlife in the Masai Mara',
                    'White-sand, reef-protected Diani Beach',
                    'Seamless bush-to-beach flight',
                    'Ideal honeymoon and family combination',
                ],
            ],
        ],
        'inclusions' => array_merge($inclusions, ['Beach accommodation on a half-board basis']),
        'exclusions' => array_merge($exclusions, ['Beach activities and watersports']),
        'faqs' => [
            ['q' => 'Is Diani the best beach in Kenya?', 'a' => 'Diani is the most famous, offering long white sand and calm water. Watamu and the Zanzibar archipelago are excellent alternatives.'],
            ['q' => 'How long should the safari be?', 'a' => 'Four safari nights is a good balance for this length; we can adjust the split to suit you.'],
            ['q' => 'Is this a good honeymoon?', 'a' => 'It is one of our most requested honeymoon structures, combining romance and adventure.'],
            ['q' => 'When should we travel?', 'a' => 'January to March and July to October offer the best safari and coast conditions.'],
        ],
        'related' => ['luxury-safari-and-beach-kenya', 'safaris/masai-mara-amboseli-diani', 'luxury-honeymoon-safaris-kenya', 'destinations/masai-mara'],
    ],

    'safaris/kenya-zanzibar-luxury-safari' => [
        'locale' => 'en',
        'group' => 'safaris/kenya-zanzibar-luxury-safari',
        'template' => 'itinerary',
        'eyebrow' => 'Two countries, one journey',
        'h1' => 'Kenya & Zanzibar Luxury Safari',
        'title' => 'Kenya Safari & Zanzibar | Luxury Bush and Beach Journey',
        'description' => 'A luxury Kenya safari and Zanzibar journey, combining the Masai Mara with the spice-island beaches of the Indian Ocean.',
        'subtitle' => 'The ultimate bush-and-beach combination — the Masai Mara\'s wildlife, then the turquoise water and Swahili culture of Zanzibar.',
        'hero_image' => 'images/safari-lion-drive.jpg',
        'hero_alt' => 'Kenya safari and Zanzibar luxury beach journey',
        'facts' => [
            ['label' => 'Duration', 'value' => '10 days / 9 nights'],
            ['label' => 'Regions', 'value' => 'Masai Mara · Zanzibar'],
            ['label' => 'Style', 'value' => 'Private safari & island'],
            ['label' => 'Pace', 'value' => 'Relaxed'],
        ],
        'itinerary' => [
            ['day' => 'Day 1', 'title' => 'Arrive in Nairobi', 'text' => 'Private transfer and a relaxed first night.'],
            ['day' => 'Day 2', 'title' => 'Fly to the Masai Mara', 'text' => 'Bush flight to the Mara and an afternoon game drive.'],
            ['day' => 'Day 3', 'title' => 'Mara full day', 'text' => 'Extended private drives tracking the Mara\'s predators.'],
            ['day' => 'Day 4', 'title' => 'Mara at leisure', 'text' => 'Bush breakfast, optional balloon safari and a final sundowner.'],
            ['day' => 'Day 5', 'title' => 'Fly to Zanzibar', 'text' => 'Connect via Nairobi to Zanzibar and transfer to your beach retreat.'],
            ['day' => 'Day 6', 'title' => 'Zanzibar beach', 'text' => 'A full day to relax, swim and enjoy the Indian Ocean.'],
            ['day' => 'Day 7', 'title' => 'Stone Town & spice', 'text' => 'Explore historic Stone Town and a spice farm, or simply unwind.'],
            ['day' => 'Day 8', 'title' => 'Zanzibar beach', 'text' => 'Dhow sailing, snorkelling or a spa afternoon.'],
            ['day' => 'Day 9', 'title' => 'Zanzibar at leisure', 'text' => 'A final unhurried day by the ocean.'],
            ['day' => 'Day 10', 'title' => 'Depart', 'text' => 'Transfer to Zanzibar airport for your onward flight.'],
        ],
        'sections' => [
            [
                'kicker' => 'Why this journey',
                'title' => 'Kenya\'s wildlife, Zanzibar\'s shores',
                'paragraphs' => [
                    'Zanzibar adds a different culture and a distinctly romantic finish to a Kenyan safari, with spice tours, historic Stone Town and idyllic beaches.',
                    'We coordinate the cross-border connection so the journey flows as one seamless holiday.',
                ],
                'bullets' => [
                    'Masai Mara big-cat safari',
                    'Zanzibar beaches and Swahili culture',
                    'Stone Town and spice-farm excursions',
                    'A romantic, two-country finish',
                ],
            ],
        ],
        'inclusions' => array_merge($inclusions, ['Zanzibar accommodation on a half-board basis']),
        'exclusions' => array_merge($exclusions, ['Zanzibar excursions not specified', 'Visa and entry fees for Tanzania']),
        'faqs' => [
            ['q' => 'Do we need a visa for Zanzibar?', 'a' => 'Yes, Tanzania has its own entry requirements. We will point you to the latest official guidance before travel.'],
            ['q' => 'How do we get from Kenya to Zanzibar?', 'a' => 'Usually a short flight via Nairobi or a direct connection, arranged as part of your itinerary.'],
            ['q' => 'Is Zanzibar good for honeymoons?', 'a' => 'It is one of the most romantic beach destinations in the Indian Ocean and pairs beautifully with a safari.'],
            ['q' => 'When is the best time?', 'a' => 'The dry seasons from January to March and June to October suit both the safari and the island.'],
        ],
        'related' => ['luxury-safari-and-beach-kenya', 'luxury-honeymoon-safaris-kenya', 'safaris/masai-mara-diani', 'kenya-luxury-safari-packages'],
    ],

];
